export const nbaTeams = [
    'Atlanta Hawks',
    'Boston Celtics',
    'Brooklyn Nets',
    'Charlotte Hornets',
    'Chicago Bulls',
    'Cleveland Cavaliers',
    'Dallas Mavericks',
    'Denver Nuggets',
    'Detroit Pistons',
    'Golden State Warriors',
    'Houston Rockets',
    'Indiana Pacers',
    'Los Angeles Clippers',
    'Los Angeles Lakers',
    'Memphis Grizzlies',
    'Miami Heat',
    'Milwaukee Bucks',
    'Minnesota Timberwolves',
    'New Orleans Pelicans',
    'New York Knicks',
    'Oklahoma City Thunder',
    'Orlando Magic',
    'Philadelphia 76ers',
    'Phoenix Suns',
    'Portland Trailblazers',
    'Sacramento Kings',
    'San Antonio Spurs',
    'Toronto Raptors',
    'Utah Jazz',
    'Washington Wizards'
]

export const nbaColours = [
    {AtlantaHawks: ["#C8102E", "#FDB927"]},
    {BostonCeltics: ["#007A33", "#000000"]},
    {BrooklynNets: ["#C6CFD4", "#000000"]},
    {CharlotteHornets: ["#00788C","#000000"]},
    {ChicagoBulls: ["#CE1141", "#000000"]},
    {ClevelandCavaliers: ["#860038", "#FDBB30"]},
    {DallasMavericks: ["#00538C", "#000000"]},
    {DenverNuggets: ["#1D428A", "#FEC524"]},
    {DetroitPistons: ["#1D42BA", "#C8102E"]},
    {GoldenStateWarriors: ["#006BB6", "#FDB927"]},
    {HoustonRockets: ["#CE1141", "#000000"]},
    {IndianaPacers: ["#002D62", "#FDBB30"]},
    {LosAngelesClippers: ["#1D428A", "#000000"]},
    {LosAngelesLakers: ["#552583", "#FDB927"]},
    {MemphisGrizzlies: ["#5D76A9", "#12173F"]},
    {MiamiHeat: ["#98002E", "#000000"]},
    {MilwaukeeBucks: ["#00471B", "#EEE1C6"]},
    {MinnesotaTimberwolves: ["#236192", "#9EA2A2"]},
    {NewOrleansPelicans: ["#85714D", "#0C2340"]},
    {NewYorkKnicks: ["#006BB6", "#F58426"]},
    {OklahomaCityThunder: ["#007AC1", "#EF3B24"]},
    {OrlandoMagic: ["#0077C0", "#C4CED4"]},
    {Philadelphia76ers: ["#ED174C", "#006BB6"]},
    {PhoenixSuns: ["#E56020", "#1D1160"]},
    {PortlandTrailblazers: ["#E03A3E", "#000000"]},
    {SacramentoKings: ["#5A2D81", "#000000"]},
    {SanAntonioSpurs: ["#C4CED4", "#000000"]},
    {TorontoRaptors: ["#CE1141", "#000000"]},
    {UtahJazz: ["#002B5C", "#F9A01B"]},
    {WashingtonWizards: ["#002B5C", "#E31837"]},
]

export const playerNames = [
    {displayName: "Achiuwa, Precious", 	
     firstName: "Precious",
     lastName: "Achiuwa",
     teamName: "Toronto Raptors",
    },
    {displayName: "Adams, Steven", 	
     firstName: "Steven",
     lastName: "Adams",
     teamName: "Memphis Grizzlies",
    },
    {displayName: "Adebayo, Bam", 	
     firstName: "Bam",
     lastName: "Adebayo",
     teamName: "Miami Heat",
    },
    {displayName: "Agbaji, Ochai", 	
     firstName: "Ochai",
     lastName: "Agbaji",
     teamName: "Utah Jazz",
    },
    {displayName: "Aldama, Santi", 	
     firstName: "Santi",
     lastName: "Aldama",
     teamName: "Memphis Grizzlies",
    },
    {displayName: "Alexander-Walker, Nickeil",
     firstName: "Nickeil",
     lastName: "Alexander-Walker",
     teamName: "Utah Jazz",
    },
    {displayName: "Allen, Grayson", 	
     firstName: "Grayson",
     lastName: "Allen",
     teamName: "Milwaukee Bucks",
    },
    {displayName: "Allen, Jarrett", 	
     firstName: "Jarrett",
     lastName: "Allen",
     teamName: "Cleveland Cavaliers",
    },
    {displayName: "Alvarado, Jose", 	
     firstName: "Jose",
     lastName: "Alvarado",
     teamName: "New Orleans Pelicans",
    },
    {displayName: "Anderson, Kyle", 	
     firstName: "Kyle",
     lastName: "Anderson",
     teamName: "Minnesota Timberwolves",
    },
    {displayName: "Antetokounmpo, Giannis", 
     firstName: "Giannis",
     lastName: "Antetokounmpo",
     teamName: "Milwaukee Bucks",
    }	,
    {displayName: "Antetokounmpo, Kostas", 	
     firstName: "Kostas",
     lastName: "Antetokounmpo",
     teamName: "Chicago Bulls",
    },
    {displayName: "Antetokounmpo, Thanasis", 
     firstName: "Thanasis",
     lastName: "Antetokounmpo",
     teamName: "Milwaukee Bucks",
    },
    {displayName: "Anthony, Cole", 	
     firstName: "Cole",
     lastName: "Anthony",
     teamName: "Orlando Magic",
    },
    {displayName: "Anunoby, O.G.", 	
     firstName: "O.G.",
     lastName: "Anunoby",
     teamName: "Toronto Raptors",
    },
    {displayName: "Arcidiacono, Ryan", 	
     firstName: "Ryan",
     lastName: "Arcidiacono",
     teamName: "New York Knicks",
    },
    {displayName: "Avdija, Deni", 	
     firstName: "Deni",
     lastName: "Avdija",
     teamName: "Washington Wizards",
    },
    {displayName: "Ayton, Deandre", 	
     firstName: "Deandre",
     lastName: "Ayton",
     teamName: "Phoenix Suns",
    },
    {displayName: "Azubuike, Udoka",
     firstName: "Udoka",
     lastName: "Azubuike",
     teamName: "Utah Jazz",
    },
    {displayName: "Badji, Ibou", 	
     firstName: "Ibou",
     lastName: "Badji",
     teamName: "Portland Trailblazers",
    },
    {displayName: "Bagley III, Marvin", 	
     firstName: "Marvin",
     lastName: "Bagley III",
     teamName: "Detroit Pistons",
    },
    {displayName: "Baldwin Jr., Patrick", 	
     firstName: "Patrick",
     lastName: "Baldwin Jr.",
     teamName: "Golden State Warriors",
    },
    {displayName: "Ball, LaMelo", 	
     firstName: "LaMelo",
     lastName: "Ball",
     teamName: "Charlotte Hornets",
    },
    {displayName: "Ball, Lonzo", 	
     firstName: "Lonzo",
     lastName: "Ball",
     teamName: "Chicago Bulls",
    },
    {displayName: "Bamba, Mo", 	
     firstName: "Mo",
     lastName: "Bamba",
     teamName: "Orlando Magic",
    },
    {displayName: "Banchero, Paolo", 	
     firstName: "Paolo",
     lastName: "Banchero",
     teamName: "Orlando Magic",
    },
    {displayName: "Bane, Desmond", 	
     firstName: "Desmond",
     lastName: "Bane",
     teamName: "Memphis Grizzlies",
    },
    {displayName: "Banton, Dalano", 	
     firstName: "Dalano",
     lastName: "Banton",
     teamName: "Toronto Raptors",
    },
    {displayName: "Barlow, Dominick", 	
     firstName: "Dominick",
     lastName: "Barlow",
     teamName: "San Antonio Spurs",
    },
    {displayName: "Barnes, Harrison", 	
     firstName: "Harrison",
     lastName: "Barnes",
     teamName: "Sacramento Kings",
    },
    {displayName: "Barnes, Scottie", 	
     firstName: "Scottie",
     lastName: "Barnes",
     teamName: "Toronto Raptors",
    },
    {displayName: "Barrett, RJ", 	
     firstName: "RJ",
     lastName: "Barrett",
     teamName: "New York Knicks",
    },
    {displayName: "Barton, Will", 	
     firstName: "Will",
     lastName: "Barton",
     teamName: "Washington Wizards",
    },
    {displayName: "Bassey, Charles", 	
     firstName: "Charles",
     lastName: "Bassey",
     teamName: "San Antonio Spurs",
    },
    {displayName: "Bates-Diop, Keita", 	
     firstName: "Keita",
     lastName: "Bates-Diop",
     teamName: "San Antonio Spurs",
    },
    {displayName: "Batum, Nicolas", 	
     firstName: "Nicolas",
     lastName: "Batum",
     teamName: "Los Angeles Clippers",
    },
    {displayName: "Bazley, Darius", 	
     firstName: "Darius",
     lastName: "Bazley",
     teamName: "Oklahoma City Thunder",
    },
    {displayName: "Beal, Bradley", 	
     firstName: "Bradley",
     lastName: "Beal",
     teamName: "Washington Wizards",
    },
    {displayName: "Beasley, Malik", 	
     firstName: "Malik",
     lastName: "Beasley",
     teamName: "Utah Jazz",
    },
    {displayName: "Beauchamp, MarJon", 	
     firstName: "MarJon",
     lastName: "Beauchamp",
     teamName: "Milwaukee Bucks",
    },
    {displayName: "Bertans, Davis", 	
     firstName: "Davis",
     lastName: "Bertans",
     teamName: "Dallas Mavericks",
    },
    {displayName: "Beverley, Patrick", 	
     firstName: "Patrick",
     lastName: "Beverley",
     teamName: "Los Angeles Lakers",
    },
    {displayName: "Bey, Saddiq", 	
     firstName: "Saddiq",
     lastName: "Bey",
     teamName: "Detroit Pistons",
    },
    {displayName: "Birch, Khem", 	
     firstName: "Khem",
     lastName: "Birch",
     teamName: "Toronto Raptors",
    },
    {displayName: "Bitadze, Goga", 	
     firstName: "Goga",
     lastName: "Bitadze",
     teamName: "Indiana Pacers",
    },
    {displayName: "Biyombo, Bismack", 	
     firstName: "Bismack",
     lastName: "Biyombo",
     teamName: "Phoenix Suns",
    },
    {displayName: "Boeheim, Buddy", 	
     firstName: "Buddy",
     lastName: "Boeheim",
     teamName: "Detroit Pistons",
    },
    {displayName: "Bogdanovic, Bogdan", 	
     firstName: "Bogdan",
     lastName: "Bogdanovic",
     teamName: "Atlanta Hawks",
    },
    {displayName: "Bogdanovic, Bojan", 	
     firstName: "Bojan",
     lastName: "Bogdanovic",
     teamName: "Detroit Pistons",
    },
    {displayName: "Bol, Bol",
     firstName: "Bol",
     lastName: "Bol",
     teamName: "Orlando Magic",
    },
    {displayName: "Bolmaro, Leandro", 	
     firstName: "Leandro",
     lastName: "Bolmaro",
     teamName: "Utah Jazz",
    },
    {displayName: "Booker, Devin", 	
     firstName: "Devin",
     lastName: "Booker",
     teamName: "Phoenix Suns",
    },
    {displayName: "Boston Jr., Brandon", 	
     firstName: "Brandon",
     lastName: "Boston Jr.",
     teamName: "Los Angeles Clippers",
    },
    {displayName: "Boucher, Chris", 	
     firstName: "Chris",
     lastName: "Boucher",
     teamName: "Toronto Raptors",
    },
    {displayName: "Bouknight, James", 	
     firstName: "James",
     lastName: "Bouknight",
     teamName: "Charlotte Hornets",
    },
    {displayName: "Bradley, Tony", 	
     firstName: "Tony",
     lastName: "Bradley",
     teamName: "Chicago Bulls",
    },
    {displayName: "Branham, Malaki", 	
     firstName: "Malaki",
     lastName: "Branham",
     teamName: "San Antonio Spurs",
    },
    {displayName: "Braun, Christian", 	
     firstName: "Christian",
     lastName: "Braun",
     teamName: "Denver Nuggets",
    },
    {displayName: "Bridges, Mikal", 	
     firstName: "Mikal",
     lastName: "Bridges",
     teamName: "Phoenix Suns",
    },
    {displayName: "Brissett, Oshae", 	
     firstName: "Oshae",
     lastName: "Brissett",
     teamName: "Indiana Pacers",
    },
    {displayName: "Brogdon, Malcolm", 	
     firstName: "Malcolm",
     lastName: "Brogdon",
     teamName: "Boston Celtics",
    },
    {displayName: "Brooks, Dillon", 	
     firstName: "Dillon",
     lastName: "Brooks",
     teamName: "Memphis Grizzlies",
    },
    {displayName: "Brown, Bruce", 	
     firstName: "Bruce",
     lastName: "Brown",
     teamName: "Denver Nuggets",
    },
    {displayName: "Brown, Jaylen", 	
     firstName: "Jaylen",
     lastName: "Brown",
     teamName: "Boston Celtics",
    },
    {displayName: "Brown, Kendall", 	
     firstName: "Kendall",
     lastName: "Brown",
     teamName: "Indiana Pacers",
    },
    {displayName: "Brown, Moses", 	
     firstName: "Moses",
     lastName: "Brown",
     teamName: "Los Angeles Clippers",
    },
    {displayName: "Brown III, Greg", 	
     firstName: "Greg",
     lastName: "Brown III",
     teamName: "Portland Trailblazers",
    },
    {displayName: "Brown Jr., Troy", 	
     firstName: "Troy",
     lastName: "Brown Jr.",
     teamName: "Los Angeles Lakers",
    },
    {displayName: "Brunson, Jalen", 	
     firstName: "Jalen",
     lastName: "Brunson",
     teamName: "New York Knicks",
    },
    {displayName: "Bryant, Thomas", 	
     firstName: "Thomas",
     lastName: "Bryant",
     teamName: "Los Angeles Lakers",
    },
    {displayName: "Bullock, Reggie", 	
     firstName: "Reggie",
     lastName: "Bullock",
     teamName: "Dallas Mavericks",
    },
    {displayName: "Burks, Alec", 	
     firstName: "Alec",
     lastName: "Burks",
     teamName: "Detroit Pistons",
    },
    {displayName: "Butler, Jimmy", 	
     firstName: "Jimmy",
     lastName: "Butler",
     teamName: "Miami Heat",
    },
    {displayName: "Butler Jr., John", 	
     firstName: "John",
     lastName: "Butler Jr.",
     teamName: "Portland Trailblazers",
    },
    {displayName: "Cain, Jamal", 	
     firstName: "Jamal",
     lastName: "Cain",
     teamName: "Miami Heat",
    },
    {displayName: "Caldwell-Pope, Kentavious",
     firstName: "Kentavious",
     lastName: "Caldwell-Pope",
     teamName: "Denver Nuggets",
    } 	,
    {displayName: "Cancar, Vlatko", 	
     firstName: "Vlatko",
     lastName: "Cancar",
     teamName: "Denver Nuggets",
    },
    {displayName: "Capela, Clint", 	
     firstName: "Clint",
     lastName: "Capela",
     teamName: "Atlanta Hawks",
    },
    {displayName: "Carey Jr., Vernon", 	
     firstName: "Vernon",
     lastName: "Carey Jr.",
     teamName: "Washington Wizards",
    },
    {displayName: "Carter, Jevon", 	
     firstName: "Jevon",
     lastName: "Carter",
     teamName: "Milwaukee Bucks",
    },
    {displayName: "Carter Jr., Wendell", 	
     firstName: "Wendell",
     lastName: "Carter Jr.",
     teamName: "Orlando Magic",
    },
    {displayName: "Caruso, Alex", 	
     firstName: "Alex",
     lastName: "Caruso",
     teamName: "Chicago Bulls",
    },
    {displayName: "Champagnie, Julian", 	
     firstName: "Julian",
     lastName: "Champagnie",
     teamName: "Philadelphia 76ers",
    },
    {displayName: "Champagnie, Justin", 	
     firstName: "Justin",
     lastName: "Champagnie",
     teamName: "Toronto Raptors",
    },
    {displayName: "Chandler, Kennedy", 	
     firstName: "Kennedy",
     lastName: "Chandler",
     teamName: "Memphis Grizzlies",
    },
    {displayName: "Christie, Max", 	
     firstName: "Max",
     lastName: "Christie",
     teamName: "Los Angeles Lakers",
    },
    {displayName: "Clarke, Brandon", 	
     firstName: "Brandon",
     lastName: "Clarke",
     teamName: "Memphis Grizzlies",
    },
    {displayName: "Clarkson, Jordan", 	
     firstName: "Jordan",
     lastName: "Clarkson",
     teamName: "Utah Jazz",
    },
    {displayName: "Claxton, Nic", 	
     firstName: "Nic",
     lastName: "Claxton",
     teamName: "Brooklyn Nets",
    },
    {displayName: "Coffey, Amir", 	
     firstName: "Amir",
     lastName: "Coffey",
     teamName: "Los Angeles Clippers",
    },
    {displayName: "Collins, John", 	
     firstName: "John",
     lastName: "Collins",
     teamName: "Atlanta Hawks",
    },
    {displayName: "Collins, Zach", 	
     firstName: "Zach",
     lastName: "Collins",
     teamName: "San Antonio Spurs",
    },
    {displayName: "Conley, Mike", 	
     firstName: "Mike",
     lastName: "Conley",
     teamName: "Utah Jazz",
    },
    {displayName: "Connaughton, Pat", 	
     firstName: "Pat",
     lastName: "Connaughton",
     teamName: "Milwaukee Bucks",
    },
    {displayName: "Covington, Robert", 	
     firstName: "Robert",
     lastName: "Covington",
     teamName: "Los Angeles Clippers",
    },
    {displayName: "Craig, Torrey", 	
     firstName: "Torrey",
     lastName: "Craig",
     teamName: "Phoenix Suns",
    },
    {displayName: "Crowder, Jae", 	
     firstName: "Jae",
     lastName: "Crowder",
     teamName: "Phoenix Suns",
    },
    {displayName: "Culver, Jarrett", 	
     firstName: "Jarrett",
     lastName: "Culver",
     teamName: "Atlanta Hawks",
    },
    {displayName: "Cunningham, Cade", 	
     firstName: "Cade",
     lastName: "Cunningham",
     teamName: "Detroit Pistons",
    },
    {displayName: "Curry, Seth", 	
     firstName: "Seth",
     lastName: "Curry",
     teamName: "Brooklyn Nets",
    },
    {displayName: "Curry, Stephen", 	
     firstName: "Stephen",
     lastName: "Curry",
     teamName: "Golden State Warriors",
    },
    {displayName: "Daniels, Dyson", 	
     firstName: "Dyson",
     lastName: "Daniels",
     teamName: "New Orleans Pelicans",
    },
    {displayName: "Davis, Anthony", 	
     firstName: "Anthony",
     lastName: "Davis",
     teamName: "Los Angeles Lakers",
    },
    {displayName: "Davis, Johnny", 	
     firstName: "Johnny",
     lastName: "Davis",
     teamName: "Washington Wizards",
    },
    {displayName: "Davis, Terence", 	
     firstName: "Terence",
     lastName: "Davis",
     teamName: "Sacramento Kings",
    },
    {displayName: "Davison, JD", 	
     firstName: "JD",
     lastName: "Davison",
     teamName: "Boston Celtics",
    },
    {displayName: "Dedmon, Dewayne", 	
     firstName: "Dewayne",
     lastName: "Dedmon",
     teamName: "Miami Heat",
    },
    {displayName: "Dellavedova, Matthew", 	
     firstName: "Matthew",
     lastName: "Dellavedova",
     teamName: "Sacramento Kings",
    },
    {displayName: "DeRozan, DeMar", 	
     firstName: "DeMar",
     lastName: "DeRozan",
     teamName: "Chicago Bulls",
    },
    {displayName: "Diabate, Moussa", 	
     firstName: "Moussa",
     lastName: "Diabate",
     teamName: "Los Angeles Clippers",
    },
    {displayName: "Diakite, Mamadi", 	
     firstName: "Mamadi",
     lastName: "Diakite",
     teamName: "Cleveland Cavaliers",
    },
    {displayName: "Diallo, Hamidou", 	
     firstName: "Hamidou",
     lastName: "Diallo",
     teamName: "Detroit Pistons",
    },
    {displayName: "Dieng, Gorgui", 	
     firstName: "Gorgui",
     lastName: "Dieng",
     teamName: "San Antonio Spurs",
    },
    {displayName: "Dieng, Ousmane", 	
     firstName: "Ousmane",
     lastName: "Dieng",
     teamName: "Oklahoma City Thunder",
    },
    {displayName: "Dinwiddie, Spencer", 	
     firstName: "Spencer",
     lastName: "Dinwiddie",
     teamName: "Dallas Mavericks",
    },
    {displayName: "DiVincenzo, Donte", 	
     firstName: "Donte",
     lastName: "DiVincenzo",
     teamName: "Golden State Warriors",
    },
    {displayName: "Doncic, Luka", 	
     firstName: "Luka",
     lastName: "Doncic",
     teamName: "Dallas Mavericks",
    },
    {displayName: "Dorsey, Tyler", 	
     firstName: "Tyler",
     lastName: "Dorsey",
     teamName: "Dallas Mavericks",
    },
    {displayName: "Dort, Luguentz", 	
     firstName: "Luguentz",
     lastName: "Dort",
     teamName: "Oklahoma City Thunder",
    },
    {displayName: "Dosunmu, Ayo", 	
     firstName: "Ayo",
     lastName: "Dosunmu",
     teamName: "Chicago Bulls",
    },
    {displayName: "Dotson, Devon", 	
     firstName: "Devon",
     lastName: "Dotson",
     teamName: "Washington Wizards",
    },
    {displayName: "Dowtin Jr., Jeff", 	
     firstName: "Jeff",
     lastName: "Dowtin Jr.",
     teamName: "Toronto Raptors",
    },
    {displayName: "Dragic, Goran", 	
     firstName: "Goran",
     lastName: "Dragic",
     teamName: "Chicago Bulls",
    },
    {displayName: "Drummond, Andre", 	
     firstName: "Andre",
     lastName: "Drummond",
     teamName: "Chicago Bulls",
    },
    {displayName: "Duarte, Chris", 	
     firstName: "Chris",
     lastName: "Duarte",
     teamName: "Indiana Pacers",
    },
    {displayName: "Duke Jr., David",	
     firstName: "David",
     lastName: "Duke Jr.",
     teamName: "Brooklyn Nets",
    },
    {displayName: "Durant, Kevin", 	
     firstName: "Kevin",
     lastName: "Durant",
     teamName: "Brooklyn Nets",
    },
    {displayName: "Duren, Jalen", 	
     firstName: "Jalen",
     lastName: "Duren",
     teamName: "Detroit Pistons",
    },
    {displayName: "Eason, Tari", 	
     firstName: "Tari",
     lastName: "Eason",
     teamName: "Houston Rockets",
    },
    {displayName: "Edwards, Anthony", 	
     firstName: "Anthony",
     lastName: "Edwards",
     teamName: "Minnesota Timberwolves",
    },
    {displayName: "Edwards, Kessler", 	
     firstName: "Kessler",
     lastName: "Edwards",
     teamName: "Brooklyn Nets",
    },
    {displayName: "Ellis, Keon", 	
     firstName: "Keon",
     lastName: "Ellis",
     teamName: "Sacramento Kings",
    },
    {displayName: "Embiid, Joel", 	
     firstName: "Joel",
     lastName: "Embiid",
     teamName: "Philadelphia 76ers",
    },
    {displayName: "Eubanks, Drew", 	
     firstName: "Drew",
     lastName: "Eubanks",
     teamName: "Portland Trailblazers",
    },
    {displayName: "Fernando, Bruno", 	
     firstName: "Bruno",
     lastName: "Fernando",
     teamName: "Houston Rockets",
    },
    {displayName: "Finney-Smith, Dorian", 	
     firstName: "Dorian",
     lastName: "Finney-Smith",
     teamName: "Dallas Mavericks",
    },
    {displayName: "Flynn, Malachi", 	
     firstName: "Malachi",
     lastName: "Flynn",
     teamName: "Toronto Raptors",
    },
    {displayName: "Fontecchio, Simone", 	
     firstName: "Simone",
     lastName: "Fontecchio",
     teamName: "Utah Jazz",
    },
    {displayName: "Forbes, Bryn", 	
     firstName: "Bryn",
     lastName: "Forbes",
     teamName: "Minnesota Timberwolves",
    },
    {displayName: "Forrest, Trent", 	
     firstName: "Trent",
     lastName: "Forrest",
     teamName: "Atlanta Hawks",
    },
    {displayName: "Fournier, Evan", 	
     firstName: "Evan",
     lastName: "Fournier",
     teamName: "New York Knicks",
    },
    {displayName: "Fox, De'Aaron", 	
     firstName: "De'Aaron",
     lastName: "Fox",
     teamName: "Sacramento Kings",
    },
    {displayName: "Fultz, Markelle", 	
     firstName: "Markelle",
     lastName: "Fultz",
     teamName: "Orlando Magic",
    },
    {displayName: "Gabriel, Wenyen", 	
     firstName: "Wenyen",
     lastName: "Gabriel",
     teamName: "Los Angeles Lakers",
    },
    {displayName: "Gafford, Daniel", 	
     firstName: "Daniel",
     lastName: "Gafford",
     teamName: "Washington Wizards",
    },
    {displayName: "Gallinari, Danilo", 	
     firstName: "Danilo",
     lastName: "Gallinari",
     teamName: "Boston Celtics",
    },
    {displayName: "Garland, Darius", 	
     firstName: "Darius",
     lastName: "Garland",
     teamName: "Cleveland Cavaliers",
    },
    {displayName: "Garuba, Usman", 	
     firstName: "Usman",
     lastName: "Garuba",
     teamName: "Houston Rockets",
    },
    {displayName: "Garza, Luka", 	
     firstName: "Luka",
     lastName: "Garza",
     teamName: "Minnesota Timberwolves",
    },
    {displayName: "Gay, Rudy", 	
     firstName: "Rudy",
     lastName: "Gay",
     teamName: "Utah Jazz",
    },
    {displayName: "George, Paul", 	
     firstName: "Paul",
     lastName: "George",
     teamName: "Los Angeles Clippers",
    },
    {displayName: "Gibson, Taj", 	
     firstName: "Taj",
     lastName: "Gibson",
     teamName: "Washington Wizards",
    },
    {displayName: "Giddey, Josh", 	
     firstName: "Josh",
     lastName: "Giddey",
     teamName: "Oklahoma City Thunder",
    },
    {displayName: "Gilgeous-Alexander, Shai", 
     firstName: "Shai",
     lastName: "Gilgeous-Alexander",
     teamName: "Oklahoma City Thunder",
    }	,
    {displayName: "Gill, Anthony", 	
     firstName: "Anthony",
     lastName: "Gill",
     teamName: "Washington Wizards",
    },
    {displayName: "Gillespie, Collin", 	
     firstName: "Collin",
     lastName: "Gillespie",
     teamName: "Denver Nuggets",
    },
    {displayName: "Gobert, Rudy", 	
     firstName: "Rudy",
     lastName: "Gobert",
     teamName: "Minnesota Timberwolves",
    },
    {displayName: "Goodwin, Jordan", 	
     firstName: "Jordan",
     lastName: "Goodwin",
     teamName: "Washington Wizards",
    },
    {displayName: "Gordon, Aaron", 	
     firstName: "Aaron",
     lastName: "Gordon",
     teamName: "Denver Nuggets",
    },
    {displayName: "Gordon, Eric", 	
     firstName: "Eric",
     lastName: "Gordon",
     teamName: "Houston Rockets",
    },
    {displayName: "Graham, Devonte",
     firstName: "Devonte",
     lastName: "Graham",
     teamName: "New Orleans Pelicans",
    },
    {displayName: "Grant, Jerami", 	
     firstName: "Jerami",
     lastName: "Grant",
     teamName: "Portland Trailblazers",
    },
    {displayName: "Green, AJ", 	
     firstName: "AJ",
     lastName: "Green",
     teamName: "Milwaukee Bucks",
    },
    {displayName: "Green, Danny", 	
     firstName: "Danny",
     lastName: "Green",
     teamName: "Memphis Grizzlies",
    },
    {displayName: "Green, Draymond", 	
     firstName: "Draymond",
     lastName: "Green",
     teamName: "Golden State Warriors",
    },
    {displayName: "Green, Jalen", 	
     firstName: "Jalen",
     lastName: "Green",
     teamName: "Houston Rockets",
    },
    {displayName: "Green, JaMychal", 	
     firstName: "JaMychal",
     lastName: "Green",
     teamName: "Golden State Warriors",
    },
    {displayName: "Green, Javonte", 	
     firstName: "Javonte",
     lastName: "Green",
     teamName: "Chicago Bulls",
    },
    {displayName: "Green, Jeff", 	
     firstName: "Jeff",
     lastName: "Green",
     teamName: "Denver Nuggets",
    },
    {displayName: "Green, Josh", 	
     firstName: "Josh",
     lastName: "Green",
     teamName: "Dallas Mavericks",
    },
    {displayName: "Griffin, AJ", 	
     firstName: "AJ",
     lastName: "Griffin",
     teamName: "Atlanta Hawks",
    },
    {displayName: "Griffin, Blake", 	
     firstName: "Blake",
     lastName: "Griffin",
     teamName: "Boston Celtics",
    },
    {displayName: "Grimes, Quentin", 	
     firstName: "Quentin",
     lastName: "Grimes",
     teamName: "New York Knicks",
    },
    {displayName: "Hachimura, Rui", 	
     firstName: "Rui",
     lastName: "Hachimura",
     teamName: "Washington Wizards",
    },
    {displayName: "Haliburton, Tyrese", 	
     firstName: "Tyrese",
     lastName: "Haliburton",
     teamName: "Indiana Pacers",
    },
    {displayName: "Hampton, R.J.", 	
     firstName: "R.J.",
     lastName: "Hampton",
     teamName: "Orlando Magic",
    },
    {displayName: "Hardaway Jr., Tim", 	
     firstName: "Tim",
     lastName: "Hardaway Jr.",
     teamName: "Dallas Mavericks",
    },
    {displayName: "Harden, James", 	
     firstName: "James",
     lastName: "Harden",
     teamName: "Philadelphia 76ers",
    },
    {displayName: "Hardy, Jaden", 	
     firstName: "Jaden",
     lastName: "Hardy",
     teamName: "Dallas Mavericks",
    },
    {displayName: "Harper Jr., Ron", 	
     firstName: "Ron",
     lastName: "Harper Jr.",
     teamName: "Toronto Raptors",
    },
    {displayName: "Harrell, Montrezl", 	
     firstName: "Montrezl",
     lastName: "Harrell",
     teamName: "Philadelphia 76ers",
    },
    {displayName: "Harris, Gary", 	
     firstName: "Gary",
     lastName: "Harris",
     teamName: "Orlando Magic",
    },
    {displayName: "Harris, Joe", 	
     firstName: "Joe",
     lastName: "Harris",
     teamName: "Brooklyn Nets",
    },
    {displayName: "Harris, Kevon", 	
     firstName: "Kevon",
     lastName: "Harris",
     teamName: "Orlando Magic",
    },
    {displayName: "Harris, Tobias", 	
     firstName: "Tobias",
     lastName: "Harris",
     teamName: "Philadelphia 76ers",
    },
    {displayName: "Hart, Josh", 	
     firstName: "Josh",
     lastName: "Hart",
     teamName: "Portland Trailblazers",
    },
    {displayName: "Hartenstein, Isaiah", 	
     firstName: "Isaiah",
     lastName: "Hartenstein",
     teamName: "New York Knicks",
    },
    {displayName: "Haslem, Udonis", 	
     firstName: "Udonis",
     lastName: "Haslem",
     teamName: "Miami Heat",
    },
    {displayName: "Hauser, Sam", 	
     firstName: "Sam",
     lastName: "Hauser",
     teamName: "Boston Celtics",
    },
    {displayName: "Hayes, Jaxson", 	
     firstName: "Jaxson",
     lastName: "Hayes",
     teamName: "New Orleans Pelicans",
    },
    {displayName: "Hayes, Killian", 	
     firstName: "Killian",
     lastName: "Hayes",
     teamName: "Detroit Pistons",
    },
    {displayName: "Hayward, Gordon", 	
     firstName: "Gordon",
     lastName: "Hayward",
     teamName: "Charlotte Hornets",
    },
    {displayName: "Hernangomez, Juancho", 	
     firstName: "Juancho",
     lastName: "Hernangomez",
     teamName: "Toronto Raptors",
    },
    {displayName: "Hernangomez, Willy", 	
     firstName: "Willy",
     lastName: "Hernangomez",
     teamName: "New Orleans Pelicans",
    },
    {displayName: "Herro, Tyler", 	
     firstName: "Tyler",
     lastName: "Herro",
     teamName: "Miami Heat",
    },
    {displayName: "Hield, Buddy", 	
     firstName: "Buddy",
     lastName: "Hield",
     teamName: "Indiana Pacers",
    },
    {displayName: "Highsmith, Haywood", 	
     firstName: "Haywood",
     lastName: "Highsmith",
     teamName: "Miami Heat",
    },
    {displayName: "Hill, George", 	
     firstName: "George",
     lastName: "Hill",
     teamName: "Milwaukee Bucks",
    },
    {displayName: "Hill, Malcolm", 	
     firstName: "Malcolm",
     lastName: "Hill",
     teamName: "Chicago Bulls",
    },
    {displayName: "Holiday, Aaron", 	
     firstName: "Aaron",
     lastName: "Holiday",
     teamName: "Atlanta Hawks",
    },
    {displayName: "Holiday, Jrue", 	
     firstName: "Jrue",
     lastName: "Holiday",
     teamName: "Milwaukee Bucks",
    },
    {displayName: "Holiday, Justin", 	
     firstName: "Justin",
     lastName: "Holiday",
     teamName: "Atlanta Hawks",
    },
    {displayName: "Holmes, Richaun", 	
     firstName: "Richaun",
     lastName: "Holmes",
     teamName: "Sacramento Kings",
    },
    {displayName: "Holmgren, Chet", 	
     firstName: "Chet",
     lastName: "Holmgren",
     teamName: "Oklahoma City Thunder",
    },
    {displayName: "Horford, Al", 	
     firstName: "Al",
     lastName: "Horford",
     teamName: "Boston Celtics",
    },
    {displayName: "Horton-Tucker, Talen", 	
     firstName: "Talen",
     lastName: "Horton-Tucker",
     teamName: "Utah Jazz",
    },
    {displayName: "House Jr., Danuel", 	
     firstName: "Danuel",
     lastName: "House Jr.",
     teamName: "Philadelphia 76ers",
    },
    {displayName: "Houstan, Caleb", 	
     firstName: "Caleb",
     lastName: "Houstan",
     teamName: "Orlando Magic",
    },
    {displayName: "Hudgins, Trevor", 	
     firstName: "Trevor",
     lastName: "Hudgins",
     teamName: "Houston Rockets",
    },
    {displayName: "Huerter, Kevin", 	
     firstName: "Kevin",
     lastName: "Huerter",
     teamName: "Sacramento Kings",
    },
    {displayName: "Hunter, De'Andre", 	
     firstName: "De'Andre",
     lastName: "Hunter",
     teamName: "Atlanta Hawks",
    },
    {displayName: "Hyland, Bones", 	
     firstName: "Bones",
     lastName: "Hyland",
     teamName: "Denver Nuggets",
    },
    {displayName: "Ibaka, Serge", 	
     firstName: "Serge",
     lastName: "Ibaka",
     teamName: "Milwaukee Bucks",
    },
    {displayName: "Iguodala, Andre", 	
     firstName: "Andre",
     lastName: "Iguodala",
     teamName: "Golden State Warriors",
    },
    {displayName: "Ingles, Joe", 	
     firstName: "Joe",
     lastName: "Ingles",
     teamName: "Milwaukee Bucks",
    },
    {displayName: "Ingram, Brandon", 	
     firstName: "Brandon",
     lastName: "Ingram",
     teamName: "New Orleans Pelicans",
    },
    {displayName: "Irving, Kyrie", 	
     firstName: "Kyrie",
     lastName: "Irving",
     teamName: "Brooklyn Nets",
    },
    {displayName: "Isaac, Jonathan", 	
     firstName: "Jonathan",
     lastName: "Isaac",
     teamName: "Orlando Magic",
    },
    {displayName: "Ivey, Jaden", 	
     firstName: "Jaden",
     lastName: "Ivey",
     teamName: "Detroit Pistons",
    },
    {displayName: "Jackson, Isaiah", 	
     firstName: "Isaiah",
     lastName: "Jackson",
     teamName: "Indiana Pacers",
    },
    {displayName: "Jackson, Justin", 	
     firstName: "Justin",
     lastName: "Jackson",
     teamName: "Boston Celtics",
    },
    {displayName: "Jackson, Reggie", 	
     firstName: "Reggie",
     lastName: "Jackson",
     teamName: "Los Angeles Clippers",
    },
    {displayName: "Jackson Jr., Jaren", 	
     firstName: "Jaren",
     lastName: "Jackson Jr.",
     teamName: "Memphis Grizzlies",
    },
    {displayName: "James, LeBron", 	
     firstName: "LeBron",
     lastName: "James",
     teamName: "Los Angeles Lakers",
    },
    {displayName: "Jerome, Ty", 	
     firstName: "Ty",
     lastName: "Jerome",
     teamName: "Golden State Warriors",
    },
    {displayName: "Joe, Isaiah", 	
     firstName: "Isaiah",
     lastName: "Joe",
     teamName: "Oklahoma City Thunder",
    },
    {displayName: "Johnson, Cameron", 	
     firstName: "Cameron",
     lastName: "Johnson",
     teamName: "Phoenix Suns",
    },
    {displayName: "Johnson, Jalen", 	
     firstName: "Jalen",
     lastName: "Johnson",
     teamName: "Atlanta Hawks",
    },
    {displayName: "Johnson, James", 	
     firstName: "James",
     lastName: "Johnson",
     teamName: "Indiana Pacers",
    },
    {displayName: "Johnson, Keldon", 	
     firstName: "Keldon",
     lastName: "Johnson",
     teamName: "San Antonio Spurs",
    },
    {displayName: "Johnson, Keon", 	
     firstName: "Keon",
     lastName: "Johnson",
     teamName: "Portland Trailblazers",
    },
    {displayName: "Johnson, Stanley", 	
     firstName: "Stanley",
     lastName: "Johnson",
     teamName: "San Antonio Spurs",
    },
    {displayName: "Jokic, Nikola", 	
     firstName: "Nikola",
     lastName: "Jokic",
     teamName: "Denver Nuggets",
    },
    {displayName: "Jones, Damian", 	
     firstName: "Damian",
     lastName: "Jones",
     teamName: "Los Angeles Lakers",
    },
    {displayName: "Jones, Herbert", 	
     firstName: "Herbert",
     lastName: "Jones",
     teamName: "New Orleans Pelicans",
    },
    {displayName: "Jones, Kai", 	
     firstName: "Kai",
     lastName: "Jones",
     teamName: "Charlotte Hornets",
    },
    {displayName: "Jones, Tre", 	
     firstName: "Tre",
     lastName: "Jones",
     teamName: "San Antonio Spurs",
    },
    {displayName: "Jones, Tyus", 	
     firstName: "Tyus",
     lastName: "Jones",
     teamName: "Memphis Grizzlies",
    },
    {displayName: "Jones Jr., Derrick", 	
     firstName: "Derrick",
     lastName: "Jones Jr.",
     teamName: "Chicago Bulls",
    },
    {displayName: "Jordan, DeAndre", 	
     firstName: "DeAndre",
     lastName: "Jordan",
     teamName: "Denver Nuggets",
    },
    {displayName: "Joseph, Cory", 	
     firstName: "Cory",
     lastName: "Joseph",
     teamName: "Detroit Pistons",
    },
    {displayName: "Jovic, Nikola", 	
     firstName: "Nikola",
     lastName: "Jovic",
     teamName: "",
    },
    {displayName: "Juzang, Johnny", 	 
     firstName: "Johnny",
     lastName: "Juzang",
     teamName: "Utah Jazz",
    },
    {displayName: "Kabengele, Mfiondu", 	
     firstName: "Mfiondu",
     lastName: "Kabengele",
     teamName: "Boston Celtics",
    },
    {displayName: "Kaminsky, Frank", 	
     firstName: "Frank",
     lastName: "Kaminsky",
     teamName: "Atlanta Hawks",
    },
    {displayName: "Keels, Trevor", 	
     firstName: "Trevor",
     lastName: "Keels",
     teamName: "New York Knicks",
    },
    {displayName: "Kennard, Luke", 	
     firstName: "Luke",
     lastName: "Kennard",
     teamName: "Los Angeles Clippers",
    },
    {displayName: "Kessler, Walker", 	
     firstName: "Walker",
     lastName: "Kessler",
     teamName: "Utah Jazz",
    },
    {displayName: "Key, Braxton", 	
     firstName: "Braxton",
     lastName: "Key",
     teamName: "Detroit Pistons",
    },
    {displayName: "Kispert, Corey", 	
     firstName: "Corey",
     lastName: "Kispert",
     teamName: "Washington Wizards",
    },
    {displayName: "Kleber, Maxi", 	
     firstName: "Maxi",
     lastName: "Kleber",
     teamName: "Dallas Mavericks",
    },
    {displayName: "Knight, Nathan", 	
     firstName: "Nathan",
     lastName: "Knight",
     teamName: "Minnesota Timberwolves",
    },
    {displayName: "Knox II, Kevin", 	
     firstName: "Kevin",
     lastName: "Knox II",
     teamName: "Detroit Pistons",
    },
    {displayName: "Koloko, Christian", 	
     firstName: "Christian",
     lastName: "Koloko",
     teamName: "Toronto Raptors",
    },
    {displayName: "Konchar, John", 	
     firstName: "John",
     lastName: "Konchar",
     teamName: "Memphis Grizzlies",
    },
    {displayName: "Korkmaz, Furkan", 	
     firstName: "Furkan",
     lastName: "Korkmaz",
     teamName: "Philadelphia 76ers",
    },
    {displayName: "Kornet, Luke", 	
     firstName: "Luke",
     lastName: "Kornet",
     teamName: "Boston Celtics",
    },
    {displayName: "Krejci, Vit", 	
     firstName: "Vit",
     lastName: "Krejci",
     teamName: "Atlanta Hawks",
    },
    {displayName: "Kuminga, Jonathan", 	
     firstName: "Jonathan",
     lastName: "Kuminga",
     teamName: "Golden State Warriors",
    },
    {displayName: "Kuzma, Kyle", 	
     firstName: "Kyle",
     lastName: "Kuzma",
     teamName: "Washington Wizards",
    },
    {displayName: "Lamb, Anthony", 	
     firstName: "Anthony",
     lastName: "Lamb",
     teamName: "Golden State Warriors",
    },
    {displayName: "Landale, Jock", 	
     firstName: "Jock",
     lastName: "Landale",
     teamName: "Phoenix Suns",
    },
    {displayName: "Langford, Romeo", 	
     firstName: "Romeo",
     lastName: "Langford",
     teamName: "San Antonio Spurs",
    },
    {displayName: "LaVine, Zach", 	
     firstName: "Zach",
     lastName: "LaVine",
     teamName: "Chicago Bulls",
    },
    {displayName: "Lee, Damion", 	
     firstName: "Damion",
     lastName: "Lee",
     teamName: "Phoenix Suns",
    },
    {displayName: "Lee, Saben", 	
     firstName: "Saben",
     lastName: "Lee",
     teamName: "Philadelphia 76ers",
    },
    {displayName: "Len, Alex", 	
     firstName: "Alex",
     lastName: "Len",
     teamName: "Sacramento Kings",
    },
    {displayName: "Leonard, Kawhi", 	
     firstName: "Kawhi",
     lastName: "Leonard",
     teamName: "Los Angeles Clippers",
    },
    {displayName: "LeVert, Caris", 	
     firstName: "Caris",
     lastName: "LeVert",
     teamName: "Cleveland Cavaliers",
    },
    {displayName: "Lewis Jr., Kira",	
     firstName: "Kira",
     lastName: "Lewis Jr.",
     teamName: "New Orleans Pelicans",
    },
    {displayName: "Liddell, E.J.", 	
     firstName: "E.J.",
     lastName: "Liddell",
     teamName: "New Orleans Pelicans",
    },
    {displayName: "Lillard, Damian", 	
     firstName: "Damian",
     lastName: "Lillard",
     teamName: "Portland Trailblazers",
    },
    {displayName: "Little, Nassir", 	
     firstName: "Nassir",
     lastName: "Little",
     teamName: "Portland Trailblazers",
    },
    {displayName: "Livers, Isaiah", 	
     firstName: "Isaiah",
     lastName: "Livers",
     teamName: "Detroit Pistons",
    },
    {displayName: "Looney, Kevon", 	
     firstName: "Kevon",
     lastName: "Looney",
     teamName: "Golden State Warriors",
    },
    {displayName: "Lopez, Brook", 	
     firstName: "Brook",
     lastName: "Lopez",
     teamName: "Milwaukee Bucks",
    },
    {displayName: "Lopez, Robin", 	
     firstName: "Robin",
     lastName: "Lopez",
     teamName: "Cleveland Cavaliers",
    },
    {displayName: "Love, Kevin", 	
     firstName: "Kevin",
     lastName: "Love",
     teamName: "Cleveland Cavaliers",
    },
    {displayName: "Lowry, Kyle", 	
     firstName: "Kyle",
     lastName: "Lowry",
     teamName: "Miami Heat",
    },
    {displayName: "Lyles, Trey", 	
     firstName: "Trey",
     lastName: "Lyles",
     teamName: "Sacramento Kings",
    },
    {displayName: "Maledon, Theo", 	
     firstName: "Theo",
     lastName: "Maledon",
     teamName: "Charlotte Hornets",
    },
    {displayName: "Mamukelashvili, Sandro", 
     firstName: "Sandro",
     lastName: "Mamukelashvili",
     teamName: "Milwaukee Bucks",
    }	,
    {displayName: "Mann, Terance", 	
     firstName: "Terance",
     lastName: "Mann",
     teamName: "Los Angeles Clippers",
    },
    {displayName: "Mann, Tre", 	
     firstName: "Tre",
     lastName: "Mann",
     teamName: "Oklahoma City Thunder",
    },
    {displayName: "Marjanovic, Boban", 	
     firstName: "Boban",
     lastName: "Marjanovic",
     teamName: "Houston Rockets",
    },
    {displayName: "Markkanen, Lauri", 	
     firstName: "Lauri",
     lastName: "Markkanen",
     teamName: "Utah Jazz",
    },
    {displayName: "Marshall, Naji", 	
     firstName: "Naji",
     lastName: "Marshall",
     teamName: "New Orleans Pelicans",
    },
    {displayName: "Martin, Caleb", 	
     firstName: "Caleb",
     lastName: "Martin",
     teamName: "Miami Heat",
    },
    {displayName: "Martin, Cody", 	
     firstName: "Cody",
     lastName: "Martin",
     teamName: "Charlotte Hornets",
    },
    {displayName: "Martin, Tyrese", 	
     firstName: "Tyrese",
     lastName: "Martin",
     teamName: "Atlanta Hawks",
    },
    {displayName: "Martin Jr., Kenyon", 	
     firstName: "Kenyon",
     lastName: "Martin Jr.",
     teamName: "Houston Rockets",
    },
    {displayName: "Mathews, Garrison", 	
     firstName: "Garrison",
     lastName: "Mathews",
     teamName: "Houston Rockets",
    },
    {displayName: "Mathurin, Bennedict", 	
     firstName: "Bennedict",
     lastName: "Mathurin",
     teamName: "Indiana Pacers",
    },
    {displayName: "Matthews, Wesley", 	
     firstName: "Wesley",
     lastName: "Matthews",
     teamName: "Milwaukee Bucks",
    },
    {displayName: "Maxey, Tyrese", 	
     firstName: "Tyrese",
     lastName: "Maxey",
     teamName: "Philadelphia 76ers",
    },
    {displayName: "McBride, Miles", 	
     firstName: "Miles",
     lastName: "McBride",
     teamName: "New York Knicks",
    },
    {displayName: "McCollum, CJ", 	
     firstName: "CJ",
     lastName: "McCollum",
     teamName: "New Orleans Pelicans",
    },
    {displayName: "McConnell, T.J.", 	
     firstName: "T.J.",
     lastName: "McConnell",
     teamName: "Indiana Pacers",
    },
    {displayName: "McDaniels, Jaden", 	
     firstName: "Jaden",
     lastName: "McDaniels",
     teamName: "Minnesota Timberwolves",
    },
    {displayName: "McDaniels, Jalen", 	
     firstName: "Jalen",
     lastName: "McDaniels",
     teamName: "Charlotte Hornets",
    },
    {displayName: "McDermott, Doug", 	
     firstName: "Doug",
     lastName: "McDermott",
     teamName: "San Antonio Spurs",
    },
    {displayName: "McGee, JaVale", 	
     firstName: "JaVale",
     lastName: "McGee",
     teamName: "Dallas Mavericks",
    },
    {displayName: "McGowens, Bryce", 	
     firstName: "Bryce",
     lastName: "McGowens",
     teamName: "Charlotte Hornets",
    },
    {displayName: "McGruder, Rodney", 	
     firstName: "Rodney",
     lastName: "McGruder",
     teamName: "Detroit Pistons",
    },
    {displayName: "McLaughlin, Jordan", 	
     firstName: "Jordan",
     lastName: "McLaughlin",
     teamName: "Minnesota Timberwolves",
    },
    {displayName: "Melton, De'Anthony", 	
     firstName: "De'Anthony",
     lastName: "Melton",
     teamName: "Philadelphia 76ers",
    },
    {displayName: "Metu, Chimezie", 	
     firstName: "Chimezie",
     lastName: "Metu",
     teamName: "Sacramento Kings",
    },
    {displayName: "Middleton, Khris", 	
     firstName: "Khris",
     lastName: "Middleton",
     teamName: "Milwaukee Bucks",
    },
    {displayName: "Mills, Patty", 	
     firstName: "Patty",
     lastName: "Mills",
     teamName: "Brooklyn Nets",
    },
    {displayName: "Milton, Shake", 	
     firstName: "Shake",
     lastName: "Milton",
     teamName: "Philadelphia 76ers",
    },
    {displayName: "Minott, Josh", 	
     firstName: "Josh",
     lastName: "Minott",
     teamName: "Minnesota Timberwolves",
    },
    {displayName: "Mitchell, Davion", 	
     firstName: "Davion",
     lastName: "Mitchell",
     teamName: "Sacramento Kings",
    },
    {displayName: "Mitchell, Donovan", 	
     firstName: "Donovan",
     lastName: "Mitchell",
     teamName: "Cleveland Cavaliers",
    },
    {displayName: "Mobley, Evan", 	
     firstName: "Evan",
     lastName: "Mobley",
     teamName: "Cleveland Cavaliers",
    },
    {displayName: "Mobley, Isaiah", 	
     firstName: "Isaiah",
     lastName: "Mobley",
     teamName: "Cleveland Cavaliers",
    },
    {displayName: "Moneke, Chima", 	
     firstName: "Chima",
     lastName: "Moneke",
     teamName: "Sacramento Kings",
    },
    {displayName: "Monk, Malik", 	
     firstName: "Malik",
     lastName: "Monk",
     teamName: "Sacramento Kings",
    },
    {displayName: "Moody, Moses", 	
     firstName: "Moses",
     lastName: "Moody",
     teamName: "Golden State Warriors",
    },
    {displayName: "Moore Jr., Wendell", 	
     firstName: "Wendell",
     lastName: "Moore Jr.",
     teamName: "Minnesota Timberwolves",
    },
    {displayName: "Morant, Ja", 	
     firstName: "Ja",
     lastName: "Morant",
     teamName: "Memphis Grizzlies",
    },
    {displayName: "Morgan, Juwan", 	
     firstName: "Juwan",
     lastName: "Morgan",
     teamName: "",
    },
    {displayName: "Morris, Markieff", 	
     firstName: "Markieff",
     lastName: "Morris",
     teamName: "Brooklyn Nets",
    },
    {displayName: "Morris, Monte", 	
     firstName: "Monte",
     lastName: "Morris",
     teamName: "Washington Wizards",
    },
    {displayName: "Morris Sr., Marcus", 	
     firstName: "Marcus",
     lastName: "Morris Sr.",
     teamName: "Los Angeles Clippers",
    },
    {displayName: "Murphy III, Trey", 	
     firstName: "Trey",
     lastName: "Murphy III",
     teamName: "New Orleans Pelicans",
    },
    {displayName: "Murray, Dejounte", 	
     firstName: "Dejounte",
     lastName: "Murray",
     teamName: "Atlanta Hawks",
    },
    {displayName: "Murray, Jamal", 	
     firstName: "Jamal",
     lastName: "Murray",
     teamName: "Denver Nuggets",
    },
    {displayName: "Murray, Keegan", 	
     firstName: "Keegan",
     lastName: "Murray",
     teamName: "Sacramento Kings",
    },
    {displayName: "Muscala, Mike", 	
     firstName: "Mike",
     lastName: "Muscala",
     teamName: "Oklahoma City Thunder",
    },
    {displayName: "Mykhailiuk, Svi", 	 
     firstName: "Svi",
     lastName: "Mykhailiuk",
     teamName: "New York Knicks",
    },
    {displayName: "Nance Jr., Larry", 	
     firstName: "Larry",
     lastName: "Nance Jr.",
     teamName: "New Orleans Pelicans",
    },
    {displayName: "Nembhard, Andrew", 	
     firstName: "Andrew",
     lastName: "Nembhard",
     teamName: "Indiana Pacers",
    },
    {displayName: "Nesmith, Aaron", 	
     firstName: "Aaron",
     lastName: "Nesmith",
     teamName: "Indiana Pacers",
    },
    {displayName: "Neto, Raul", 	
     firstName: "Raul",
     lastName: "Neto",
     teamName: "Cleveland Cavaliers",
    },
    {displayName: "Niang, Georges", 	
     firstName: "Georges",
     lastName: "Niang",
     teamName: "Philadelphia 76ers",
    },
    {displayName: "Nix, Daishen", 	
     firstName: "Daishen",
     lastName: "Nix",
     teamName: "Houston Rockets",
    },
    {displayName: "Nnaji, Zeke", 	
     firstName: "Zeke",
     lastName: "Nnaji",
     teamName: "Denver Nuggets",
    },
    {displayName: "Noel, Nerlens", 	
     firstName: "Nerlens",
     lastName: "Noel",
     teamName: "Detroit Pistons",
    },
    {displayName: "Nowell, Jaylen", 	
     firstName: "Jaylen",
     lastName: "Nowell",
     teamName: "Minnesota Timberwolves",
    },
    {displayName: "Ntilikina, Frank", 	
     firstName: "Frank",
     lastName: "Ntilikina",
     teamName: "Dallas Mavericks",
    },
    {displayName: "Nunn, Kendrick", 	
     firstName: "Kendrick",
     lastName: "Nunn",
     teamName: "Los Angeles Lakers",
    },
    {displayName: "Nurkic, Jusuf", 	
     firstName: "Jusuf",
     lastName: "Nurkic",
     teamName: "Portland Trailblazers",
    },
    {displayName: "Nwora, Jordan", 	
     firstName: "Jordan",
     lastName: "Nwora",
     teamName: "Milwaukee Bucks",
    },
    {displayName: "Okeke, Chuma", 	
     firstName: "Chuma",
     lastName: "Okeke",
     teamName: "Orlando Magic",
    },
    {displayName: "Okogie, Josh", 	
     firstName: "Josh",
     lastName: "Okogie",
     teamName: "Phoenix Suns",
    },
    {displayName: "Okongwu, Onyeka", 	
     firstName: "Onyeka",
     lastName: "Okongwu",
     teamName: "Atlanta Hawks",
    },
    {displayName: "Okoro, Isaac", 	
     firstName: "Isaac",
     lastName: "Okoro",
     teamName: "Cleveland Cavaliers",
    },
    {displayName: "Okpala, KZ", 	
     firstName: "KZ",
     lastName: "Okpala",
     teamName: "Sacramento Kings",
    },
    {displayName: "Oladipo, Victor", 	
     firstName: "Victor",
     lastName: "Oladipo",
     teamName: "Miami Heat",
    },
    {displayName: "Olynyk, Kelly", 	
     firstName: "Kelly",
     lastName: "Olynyk",
     teamName: "Utah Jazz",
    },
    {displayName: "Omoruyi, Eugene", 	
     firstName: "Eugene",
     lastName: "Omoruyi",
     teamName: "Oklahoma City Thunder",
    },
    {displayName: "O'Neale, Royce", 	
     firstName: "Royce",
     lastName: "O'Neale",
     teamName: "Brooklyn Nets",
    },
    {displayName: "Osman, Cedi", 	
     firstName: "Cedi",
     lastName: "Osman",
     teamName: "Cleveland Cavaliers",
    },
    {displayName: "Oubre Jr., Kelly", 	 
     firstName: "Kelly",
     lastName: "Oubre Jr.",
     teamName: "Charlotte Hornets",
    },
    {displayName: "Paul, Chris", 	
     firstName: "Chris",
     lastName: "Paul",
     teamName: "Phoenix Suns",
    },
    {displayName: "Payne, Cameron", 	
     firstName: "Cameron",
     lastName: "Payne",
     teamName: "Phoenix Suns",
    },
    {displayName: "Payton II, Gary", 	
     firstName: "Gary",
     lastName: "Payton II",
     teamName: "Portland Trailblazers",
    },
    {displayName: "Pinson, Theo", 	
     firstName: "Theo",
     lastName: "Pinson",
     teamName: "Dallas Mavericks",
    },
    {displayName: "Pippen Jr., Scotty", 	
     firstName: "Scotty",
     lastName: "Pippen Jr.",
     teamName: "Los Angeles Lakers",
    },
    {displayName: "Plumlee, Mason", 	
     firstName: "Mason",
     lastName: "Plumlee",
     teamName: "Charlotte Hornets",
    },
    {displayName: "Poeltl, Jakob", 	
     firstName: "Jakob",
     lastName: "Poeltl",
     teamName: "San Antonio Spurs",
    },
    {displayName: "Pokusevski, Aleksej", 	
     firstName: "Aleksej",
     lastName: "Pokusevski",
     teamName: "Oklahoma City Thunder",
    },
    {displayName: "Poole, Jordan", 	
     firstName: "Jordan",
     lastName: "Poole",
     teamName: "Golden State Warriors",
    },
    {displayName: "Porter Jr., Kevin", 	
     firstName: "Kevin",
     lastName: "Porter Jr.",
     teamName: "Houston Rockets",
    },
    {displayName: "Porter Jr., Michael", 	
     firstName: "Michael",
     lastName: "Porter Jr.",
     teamName: "Denver Nuggets",
    },
    {displayName: "Porter Jr., Otto", 	
     firstName: "Otto",
     lastName: "Porter Jr.",
     teamName: "Toronto Raptors",
    },
    {displayName: "Portis, Bobby", 	
     firstName: "Bobby",
     lastName: "Portis",
     teamName: "Milwaukee Bucks",
    },
    {displayName: "Porzingis, Kristaps", 	
     firstName: "Kristaps",
     lastName: "Porzingis",
     teamName: "Washington Wizards",
    },
    {displayName: "Potter, Micah", 	
     firstName: "Micah",
     lastName: "Potter",
     teamName: "Utah Jazz",
    },
    {displayName: "Powell, Dwight", 	
     firstName: "Dwight",
     lastName: "Powell",
     teamName: "Dallas Mavericks",
    },
    {displayName: "Powell, Norman", 	
     firstName: "Norman",
     lastName: "Powell",
     teamName: "Los Angeles Clippers",
    },
    {displayName: "Preston, Jason", 	
     firstName: "Jason",
     lastName: "Preston",
     teamName: "Los Angeles Clippers",
    },
    {displayName: "Prince, Taurean", 	
     firstName: "Taurean",
     lastName: "Prince",
     teamName: "Minnesota Timberwolves",
    },
    {displayName: "Pritchard, Payton", 	
     firstName: "Payton",
     lastName: "Pritchard",
     teamName: "Boston Celtics",
    },
    {displayName: "Procida, Gabriele", 	
     firstName: "Gabriele",
     lastName: "Procida",
     teamName: "",
    },
    {displayName: "Queen, Trevelin", 	
     firstName: "Trevelin",
     lastName: "Queen",
     teamName: "Indiana Pacers",
    },
    {displayName: "Queta, Neemias", 	
     firstName: "Neemias",
     lastName: "Queta",
     teamName: "Sacramento Kings",
    },
    {displayName: "Quickley, Immanuel", 	
     firstName: "Immanuel",
     lastName: "Quickley",
     teamName: "New York Knicks",
    },
    {displayName: "Randle, Julius", 	
     firstName: "Julius",
     lastName: "Randle",
     teamName: "New York Knicks",
    },
    {displayName: "Reaves, Austin", 	
     firstName: "Austin",
     lastName: "Reaves",
     teamName: "Los Angeles Lakers",
    },
    {displayName: "Reddish, Cam", 	
     firstName: "Cam",
     lastName: "Reddish",
     teamName: "New York Knicks",
    },
    {displayName: "Reed, Davon", 	
     firstName: "Davon",
     lastName: "Reed",
     teamName: "Denver Nuggets",
    },
    {displayName: "Reed, Paul", 	
     firstName: "Paul",
     lastName: "Reed",
     teamName: "Philadelphia 76ers",
    },
    {displayName: "Reid, Naz", 	
     firstName: "Naz",
     lastName: "Reid",
     teamName: "Minnesota Timberwolves",
    },
    {displayName: "Richards, Nick", 	
     firstName: "Nick",
     lastName: "Richards",
     teamName: "Charlotte Hornets",
    },
    {displayName: "Richardson, Josh", 	
     firstName: "Josh",
     lastName: "Richardson",
     teamName: "San Antonio Spurs",
    },
    {displayName: "Rivers, Austin", 	
     firstName: "Austin",
     lastName: "Rivers",
     teamName: "Minnesota Timberwolves",
    },
    {displayName: "Robinson, Duncan", 	
     firstName: "Duncan",
     lastName: "Robinson",
     teamName: "Miami Heat",
    },
    {displayName: "Robinson, Mitchell", 	
     firstName: "Mitchell",
     lastName: "Robinson",
     teamName: "New York Knicks",
    },
    {displayName: "Robinson, Orlando", 	
     firstName: "Orlando",
     lastName: "Robinson",
     teamName: "Miami Heat",
    },
    {displayName: "Robinson-Earl, Jeremiah", 
     firstName: "Jeremiah",
     lastName: "Robinson-Earl",
     teamName: "Oklahoma City Thunder",
    }	,
    {displayName: "Roby, Isaiah", 	
     firstName: "Isaiah",
     lastName: "Roby",
     teamName: "San Antonio Spurs",
    },
    {displayName: "Roddy, David", 	
     firstName: "David",
     lastName: "Roddy",
     teamName: "Memphis Grizzlies",
    },
    {displayName: "Rollins, Ryan", 	
     firstName: "Ryan",
     lastName: "Rollins",
     teamName: "Golden State Warriors",
    },
    {displayName: "Rose, Derrick", 	
     firstName: "Derrick",
     lastName: "Rose",
     teamName: "New York Knicks",
    },
    {displayName: "Ross, Terrence", 	
     firstName: "Terrence",
     lastName: "Ross",
     teamName: "Orlando Magic",
    },
    {displayName: "Rozier, Terry", 	
     firstName: "Terry",
     lastName: "Rozier",
     teamName: "Charlotte Hornets",
    },
    {displayName: "Rubio, Ricky", 	
     firstName: "Ricky",
     lastName: "Rubio",
     teamName: "Cleveland Cavaliers",
    },
    {displayName: "Russell, D'Angelo", 	
     firstName: "D'Angelo",
     lastName: "Russell",
     teamName: "Minnesota Timberwolves",
    },
    {displayName: "Ryan, Matt", 	 
     firstName: "Matt",
     lastName: "Ryan",
     teamName: "Minnesota Timberwolves",
    },
    {displayName: "Sabonis, Domantas", 	
     firstName: "Domantas",
     lastName: "Sabonis",
     teamName: "Sacramento Kings",
    },
    {displayName: "Saric, Dario", 	
     firstName: "Dario",
     lastName: "Saric",
     teamName: "Phoenix Suns",
    },
    {displayName: "Schofield, Admiral", 	
     firstName: "Admiral",
     lastName: "Schofield",
     teamName: "Orlando Magic",
    },
    {displayName: "Schroder, Dennis", 	
     firstName: "Dennis",
     lastName: "Schroder",
     teamName: "Los Angeles Lakers",
    },
    {displayName: "Seabron, Dereon", 	
     firstName: "Dereon",
     lastName: "Seabron",
     teamName: "New Orleans Pelicans",
    },
    {displayName: "Sengun, Alperen", 	
     firstName: "Alperen",
     lastName: "Sengun",
     teamName: "Houston Rockets",
    },
    {displayName: "Sexton, Collin", 	
     firstName: "Collin",
     lastName: "Sexton",
     teamName: "Utah Jazz",
    },
    {displayName: "Shamet, Landry", 	
     firstName: "Landry",
     lastName: "Shamet",
     teamName: "Phoenix Suns",
    },
    {displayName: "Sharpe, Shaedon", 	
     firstName: "Shaedon",
     lastName: "Sharpe",
     teamName: "Portland Trailblazers",
    },
    {displayName: "Siakam, Pascal", 	
     firstName: "Pascal",
     lastName: "Siakam",
     teamName: "Toronto Raptors",
    },
    {displayName: "Simmons, Ben", 	
     firstName: "Ben",
     lastName: "Simmons",
     teamName: "Brooklyn Nets",
    },
    {displayName: "Simonovic, Marko", 	
     firstName: "Marko",
     lastName: "Simonovic",
     teamName: "Chicago Bulls",
    },
    {displayName: "Simons, Anfernee", 	
     firstName: "Anfernee",
     lastName: "Simons",
     teamName: "Portland Trailblazers",
    },
    {displayName: "Sims, Jericho", 	
     firstName: "Jericho",
     lastName: "Sims",
     teamName: "New York Knicks",
    },
    {displayName: "Smart, Marcus", 	
     firstName: "Marcus",
     lastName: "Smart",
     teamName: "Boston Celtics",
    },
    {displayName: "Smith, Ish", 	
     firstName: "Ish",
     lastName: "Smith",
     teamName: "Denver Nuggets",
    },
    {displayName: "Smith, Jalen", 	
     firstName: "Jalen",
     lastName: "Smith",
     teamName: "Indiana Pacers",
    },
    {displayName: "Smith Jr., Dennis", 	
     firstName: "Dennis",
     lastName: "Smith Jr.",
     teamName: "Charlotte Hornets",
    },
    {displayName: "Smith Jr., Jabari", 	
     firstName: "Jabari",
     lastName: "Smith Jr.",
     teamName: "Houston Rockets",
    },
    {displayName: "Sochan, Jeremy", 	
     firstName: "Jeremy",
     lastName: "Sochan",
     teamName: "San Antonio Spurs",
    },
    {displayName: "Springer, Jaden", 	
     firstName: "Jaden",
     lastName: "Springer",
     teamName: "Philadelphia 76ers",
    },
    {displayName: "Stevens, Lamar", 	
     firstName: "Lamar",
     lastName: "Stevens",
     teamName: "Cleveland Cavaliers",
    },
    {displayName: "Stewart, Isaiah", 	
     firstName: "Isaiah",
     lastName: "Stewart",
     teamName: "Detroit Pistons",
    },
    {displayName: "Strus, Max", 	
     firstName: "Max",
     lastName: "Strus",
     teamName: "Miami Heat",
    },
    {displayName: "Suggs, Jalen", 	
     firstName: "Jalen",
     lastName: "Suggs",
     teamName: "Orlando Magic",
    },
    {displayName: "Sumner, Edmond", 	
     firstName: "Edmond",
     lastName: "Sumner",
     teamName: "Brooklyn Nets",
    },
    {displayName: "Swider, Cole", 	
     firstName: "Cole",
     lastName: "Swider",
     teamName: "Los Angeles Lakers",
    },
    {displayName: "Tate, Jae'Sean", 	
     firstName: "Jae'Sean",
     lastName: "Tate",
     teamName: "Houston Rockets",
    },
    {displayName: "Tatum, Jayson", 	
     firstName: "Jayson",
     lastName: "Tatum",
     teamName: "Boston Celtics",
    },
    {displayName: "Taylor, Terry", 	
     firstName: "Terry",
     lastName: "Taylor",
     teamName: "Indiana Pacers",
    },
    {displayName: "Temple, Garrett", 	
     firstName: "Garrett",
     lastName: "Temple",
     teamName: "New Orleans Pelicans",
    },
    {displayName: "Terry, Dalen", 	
     firstName: "Dalen",
     lastName: "Terry",
     teamName: "Chicago Bulls",
    },
    {displayName: "Theis, Daniel", 	
     firstName: "Daniel",
     lastName: "Theis",
     teamName: "Indiana Pacers",
    },
    {displayName: "Thomas, Cam", 	
     firstName: "Cam",
     lastName: "Thomas",
     teamName: "Brooklyn Nets",
    },
    {displayName: "Thompson, Klay", 	
     firstName: "Klay",
     lastName: "Thompson",
     teamName: "Golden State Warriors",
    },
    {displayName: "Thor, JT", 	
     firstName: "JT",
     lastName: "Thor",
     teamName: "Charlotte Hornets",
    },
    {displayName: "Thybulle, Matisse", 	
     firstName: "Matisse",
     lastName: "Thybulle",
     teamName: "Philadelphia 76ers",
    },
    {displayName: "Tillman, Xavier", 	
     firstName: "Xavier",
     lastName: "Tillman",
     teamName: "Memphis Grizzlies",
    },
    {displayName: "Todd, Isaiah", 	
     firstName: "Isaiah",
     lastName: "Todd",
     teamName: "Washington Wizards",
    },
    {displayName: "Toppin, Obi", 	
     firstName: "Obi",
     lastName: "Toppin",
     teamName: "New York Knicks",
    },
    {displayName: "Toscano-Anderson, Juan", 
     firstName: "Juan",
     lastName: "Toscano-Anderson",
     teamName: "Los Angeles Lakers",
    }	,
    {displayName: "Towns, Karl-Anthony", 	
     firstName: "Karl-Anthony",
     lastName: "Towns",
     teamName: "Minnesota Timberwolves",
    },
    {displayName: "Trent Jr., Gary", 	
     firstName: "Gary",
     lastName: "Trent Jr.",
     teamName: "Toronto Raptors",
    },
    {displayName: "Tucker, P.J.", 	
     firstName: "P.J.",
     lastName: "Tucker",
     teamName: "Philadelphia 76ers",
    },
    {displayName: "Turner, Myles", 	
     firstName: "Myles",
     lastName: "Turner",
     teamName: "Indiana Pacers",
    },
    {displayName: "Valanciunas, Jonas", 	
     firstName: "Jonas",
     lastName: "Valanciunas",
     teamName: "New Orleans Pelicans",
    },
    {displayName: "Vanderbilt, Jarred", 	
     firstName: "Jarred",
     lastName: "Vanderbilt",
     teamName: "Utah Jazz",
    },
    {displayName: "VanVleet, Fred", 	
     firstName: "Fred",
     lastName: "VanVleet",
     teamName: "Toronto Raptors",
    },
    {displayName: "Vassell, Devin", 	
     firstName: "Devin",
     lastName: "Vassell",
     teamName: "San Antonio Spurs",
    },
    {displayName: "Vincent, Gabe", 	
     firstName: "Gabe",
     lastName: "Vincent",
     teamName: "Miami Heat",
    },
    {displayName: "Vonleh, Noah", 	
     firstName: "Noah",
     lastName: "Vonleh",
     teamName: "Boston Celtics",
    },
    {displayName: "Vucevic, Nikola", 	
     firstName: "Nikola",
     lastName: "Vucevic",
     teamName: "Chicago Bulls",
    },
    {displayName: "Wade, Dean", 	
     firstName: "Dean",
     lastName: "Wade",
     teamName: "Cleveland Cavaliers",
    },
    {displayName: "Wagner, Franz", 	
     firstName: "Franz",
     lastName: "Wagner",
     teamName: "Orlando Magic",
    },
    {displayName: "Wagner, Moritz", 	
     firstName: "Moritz",
     lastName: "Wagner",
     teamName: "Orlando Magic",
    },
    {displayName: "Wainright, Ish", 	
     firstName: "Ish",
     lastName: "Wainright",
     teamName: "Phoenix Suns",
    },
    {displayName: "Walker, Jabari", 	
     firstName: "Jabari",
     lastName: "Walker",
     teamName: "Portland Trailblazers",
    },
    {displayName: "Walker, Kemba", 	
     firstName: "Kemba",
     lastName: "Walker",
     teamName: "Dallas Mavericks",
    },
    {displayName: "Walker IV, Lonnie", 	
     firstName: "Lonnie",
     lastName: "Walker IV",
     teamName: "Los Angeles Lakers",
    },
    {displayName: "Wall, John",	
     firstName: "John",
     lastName: "Wall",
     teamName: "Los Angeles Clippers",
    },
    {displayName: "Warren, T.J.", 	
     firstName: "T.J.",
     lastName: "Warren",
     teamName: "Brooklyn Nets",
    },
    {displayName: "Washington, P.J.", 	
     firstName: "P.J.",
     lastName: "Washington",
     teamName: "Charlotte Hornets",
    },
    {displayName: "Washington Jr., Duane", 	
     firstName: "Duane",
     lastName: "Washington Jr.",
     teamName: "Phoenix Suns",
    },
    {displayName: "Washington Jr., TyTy", 	
     firstName: "TyTy",
     lastName: "Washington Jr.",
     teamName: "Houston Rockets",
    },
    {displayName: "Watanabe, Yuta", 	
     firstName: "Yuta",
     lastName: "Watanabe",
     teamName: "Brooklyn Nets",
    },
    {displayName: "Waters III, Lindy", 	
     firstName: "Lindy",
     lastName: "Waters III",
     teamName: "Oklahoma City Thunder",
    },
    {displayName: "Watford, Trendon", 	
     firstName: "Trendon",
     lastName: "Watford",
     teamName: "Portland Trailblazers",
    },
    {displayName: "Watson, Peyton", 	
     firstName: "Peyton",
     lastName: "Watson",
     teamName: "Denver Nuggets",
    },
    {displayName: "Wesley, Blake", 	
     firstName: "Blake",
     lastName: "Wesley",
     teamName: "San Antonio Spurs",
    },
    {displayName: "Westbrook, Russell", 	
     firstName: "Russell",
     lastName: "Westbrook",
     teamName: "Los Angeles Lakers",
    },
    {displayName: "White, Coby", 	
     firstName: "Coby",
     lastName: "White",
     teamName: "Chicago Bulls",
    },
    {displayName: "White, Derrick", 	
     firstName: "Derrick",
     lastName: "White",
     teamName: "Boston Celtics",
    },
    {displayName: "White, Jack", 	
     firstName: "Jack",
     lastName: "White",
     teamName: "Denver Nuggets",
    },
    {displayName: "Wiggins, Aaron", 	
     firstName: "Aaron",
     lastName: "Wiggins",
     teamName: "Oklahoma City Thunder",
    },
    {displayName: "Wiggins, Andrew", 	
     firstName: "Andrew",
     lastName: "Wiggins",
     teamName: "Golden State Warriors",
    },
    {displayName: "Williams, Alondes", 	
     firstName: "Alondes",
     lastName: "Williams",
     teamName: "Brooklyn Nets",
    },
    {displayName: "Williams, Grant", 	
     firstName: "Grant",
     lastName: "Williams",
     teamName: "Boston Celtics",
    },
    {displayName: "Williams, Jalen", 	
     firstName: "Jalen",
     lastName: "Williams",
     teamName: "Oklahoma City Thunder",
    },
    {displayName: "Williams, Jaylin", 	
     firstName: "Jaylin",
     lastName: "Williams",
     teamName: "Oklahoma City Thunder",
    },
    {displayName: "Williams, Kenrich", 	
     firstName: "Kenrich",
     lastName: "Williams",
     teamName: "Oklahoma City Thunder",
    },
    {displayName: "Williams, Mark", 	
     firstName: "Mark",
     lastName: "Williams",
     teamName: "Charlotte Hornets",
    },
    {displayName: "Williams, Patrick", 	
     firstName: "Patrick",
     lastName: "Williams",
     teamName: "Chicago Bulls",
    },
    {displayName: "Williams, Ziaire", 	
     firstName: "Ziaire",
     lastName: "Williams",
     teamName: "Memphis Grizzlies",
    },
    {displayName: "Williams III, Robert", 	
     firstName: "Robert",
     lastName: "Williams III",
     teamName: "Boston Celtics",
    },
    {displayName: "Williams Jr., Vince", 	
     firstName: "Vince",
     lastName: "Williams Jr.",
     teamName: "Memphis Grizzlies",
    },
    {displayName: "Williamson, Zion", 	
     firstName: "Zion",
     lastName: "Williamson",
     teamName: "New Orleans Pelicans",
    },
    {displayName: "Windler, Dylan", 	
     firstName: "Dylan",
     lastName: "Windler",
     teamName: "Cleveland Cavaliers",
    },
    {displayName: "Winslow, Justise", 	
     firstName: "Justise",
     lastName: "Winslow",
     teamName: "Portland Trailblazers",
    },
    {displayName: "Wiseman, James", 	
     firstName: "James",
     lastName: "Wiseman",
     teamName: "Golden State Warriors",
    },
    {displayName: "Wood, Christian", 	
     firstName: "Christian",
     lastName: "Wood",
     teamName: "Dallas Mavericks",
    },
    {displayName: "Wright, Delon", 	
     firstName: "Delon",
     lastName: "Wright",
     teamName: "Washington Wizards",
    },
    {displayName: "Wright IV, McKinley", 
     firstName: "McKinley",
     lastName: "Wright IV",
     teamName: "Dallas Mavericks",
    },
    {displayName: "Young, Thaddeus", 	
     firstName: "Thaddeus",
     lastName: "Young",
     teamName: "Toronto Raptors",
    },
    {displayName: "Young, Trae", 	
     firstName: "Trae",
     lastName: "Young",
     teamName: "Atlanta Hawks",
    },
    {displayName: "Yurtseven, Omer", 	
     firstName: "Omer",
     lastName: "Yurtseven",
     teamName: "Miami Heat",
    },
    {displayName: "Zubac, Ivica",
     firstName: "Ivica",
     lastName: "Zubac",
     teamName: "Los Angeles Clippers",
    },
]	